import type { MetadataRoute } from "next";

import { blogPosts } from "@/lib/blog-posts";
import { DEMO_CLIPS, DEMO_PUBLISHED_AT, DEMO_SOURCE } from "@/lib/demo";
import { seoPages } from "@/lib/seo-pages";
import { getSiteUrl } from "@/lib/site";

export default function sitemap(): MetadataRoute.Sitemap {
  const siteUrl = getSiteUrl();
  const currentDate = new Date("2026-07-27T00:00:00.000Z");
  const latestBlogUpdate = new Date(Math.max(...blogPosts.map(post => new Date(`${post.updatedAt}T00:00:00.000Z`).getTime())));

  return [
    {
      url: siteUrl,
      lastModified: new Date("2026-10-05T00:00:00.000Z"),
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${siteUrl}/demo`,
      lastModified: new Date("2026-10-05T00:00:00.000Z"),
      changeFrequency: "monthly",
      priority: 0.9,
      videos: DEMO_CLIPS.map((clip) => ({
        title: clip.hook,
        description: `Vertical clip generated by SupoClip from "${DEMO_SOURCE.title}" (${clip.range}).`,
        thumbnail_loc: `${siteUrl}${clip.poster}`,
        content_loc: `${siteUrl}${clip.src}`,
        duration: clip.previewSeconds,
        publication_date: DEMO_PUBLISHED_AT,
      })),
    },
    ...seoPages.map((page) => ({
      url: `${siteUrl}/${page.slug}`,
      lastModified: new Date(`${page.updatedAt}T00:00:00.000Z`),
      changeFrequency: "monthly" as const,
      priority: 0.9,
    })),
    {
      url: `${siteUrl}/blog`,
      lastModified: latestBlogUpdate,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    ...blogPosts.map((post) => ({
      url: `${siteUrl}/blog/${post.slug}`,
      images: post.image ? [`${siteUrl}${post.image.src}`] : undefined,
      lastModified: new Date(`${post.updatedAt}T00:00:00.000Z`),
      changeFrequency: "monthly" as const,
      priority: 0.8,
    })),
    {
      url: `${siteUrl}/affiliate`,
      lastModified: new Date("2026-10-09T00:00:00.000Z"),
      changeFrequency: "monthly",
      priority: 0.6,
      videos: [
        {
          title: "How the SupoClip creator program works",
          description: "Apply, pick your code, and your audience gets 20% off their first 3 months.",
          thumbnail_loc: `${siteUrl}/videos/creator-program-poster.jpg`,
          content_loc: `${siteUrl}/videos/creator-program.mp4`,
          duration: 27,
          publication_date: "2026-10-09",
        },
      ],
    },
    {
      url: `${siteUrl}/privacy`,
      lastModified: new Date("2026-10-05T00:00:00.000Z"),
      changeFrequency: "yearly",
      priority: 0.2,
    },
    {
      url: `${siteUrl}/terms`,
      lastModified: currentDate,
      changeFrequency: "yearly",
      priority: 0.2,
    },
  ];
}
