from __future__ import annotations

from html import escape
from typing import Optional

from ..config import Config
from ..models import User
from .email_service import EmailContent, SesEmailService, first_name_for


class PasswordResetEmailService:
    """Send the password reset link generated by Better Auth."""

    def __init__(self, config: Optional[Config] = None):
        self.config = config or Config()
        self.email_service = SesEmailService(self.config)

    @property
    def is_configured(self) -> bool:
        return self.email_service.is_configured

    async def send_reset_email(self, user: User, reset_url: str) -> dict:
        content = self._build_reset_email(user, reset_url)
        return await self.email_service.send_email(user.email, content)

    def _build_reset_email(self, user: User, reset_url: str) -> EmailContent:
        first_name = first_name_for(first_name=user.first_name, full_name=user.name)
        safe_url = escape(reset_url, quote=True)

        return EmailContent(
            subject="Reset your SupoClip password",
            html=(
                f"<p>Hi {escape(first_name)},</p>"
                "<p>We received a request to reset the password for your SupoClip account.</p>"
                f'<p><a href="{safe_url}">Reset your password</a></p>'
                "<p>This link expires in 1 hour. If you did not request a password reset, "
                "you can ignore this email; your password will not change.</p>"
                "<p>Team SupoClip</p>"
            ),
            text=(
                f"Hi {first_name},\n\n"
                "We received a request to reset the password for your SupoClip account.\n\n"
                f"Reset your password: {reset_url}\n\n"
                "This link expires in 1 hour. If you did not request a password reset, "
                "you can ignore this email; your password will not change.\n\n"
                "Team SupoClip"
            ),
        )
