import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Captions, ExternalLink, Github, Info, ScanFace, Sparkles, Type, Youtube } from "lucide-react";

import { RelatedGuides } from "@/components/marketing/related-guides";
import { SiteFooter } from "@/components/marketing/site-footer";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DEMO_CLIPS, DEMO_PUBLISHED_AT, DEMO_SOURCE, getDemoSourceMomentUrl } from "@/lib/demo";
import { SELF_HOSTING_GUIDE_HREF } from "@/lib/marketing-links";
import { GITHUB_URL, getSiteUrl } from "@/lib/site";

const title = "SupoClip Demo: Real AI Clips from a Long Video";
const description =
  "Watch vertical, captioned clips SupoClip generated from a long-form interview, with the original timestamps, hook titles, and an explanation of each pipeline step.";

export const metadata: Metadata = {
  title: { absolute: title },
  description,
  alternates: { canonical: `${getSiteUrl()}/demo` },
  openGraph: {
    title,
    description,
    url: `${getSiteUrl()}/demo`,
    siteName: "SupoClip",
    type: "website",
    videos: DEMO_CLIPS.map((clip) => ({ url: `${getSiteUrl()}${clip.src}`, width: 540, height: 960, type: "video/mp4" })),
  },
  twitter: { card: "summary_large_image", title, description },
};

const pipeline = [
  { icon: Type, title: "Transcribe", detail: "The source audio is transcribed with word-level timestamps." },
  { icon: Sparkles, title: "Select moments", detail: "An LLM reads the transcript, proposes self-contained segments, and scores each on hook, engagement, value, and shareability." },
  { icon: Captions, title: "Write a hook", detail: "Each clip gets a short hook title, burned into the top of the frame for the first few seconds." },
  { icon: ScanFace, title: "Reframe to 9:16", detail: "Each shot is classified. Close shots get a crop that tracks the speaker's face. Wide shots, like the opening of both clips, show the full frame over a blurred background. Switches line up with the source's scene cuts." },
];

export default function DemoPage() {
  const siteUrl = getSiteUrl();
  const structuredData = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "SupoClip", item: siteUrl },
          { "@type": "ListItem", position: 2, name: "Demo", item: `${siteUrl}/demo` },
        ],
      },
      ...DEMO_CLIPS.map((clip) => ({
        "@type": "VideoObject",
        name: clip.hook,
        description: `Vertical clip generated by SupoClip from "${DEMO_SOURCE.title}" (${clip.range}). Web preview of a ${clip.duration} clip.`,
        thumbnailUrl: `${siteUrl}${clip.poster}`,
        contentUrl: `${siteUrl}${clip.src}`,
        uploadDate: DEMO_PUBLISHED_AT,
        duration: `PT${clip.previewSeconds}S`,
        isBasedOn: DEMO_SOURCE.url,
      })),
    ],
  };

  return (
    <main className="min-h-screen bg-background text-foreground">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
      <header className="border-b bg-background/95">
        <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2.5">
            <Image src="/logo.png" alt="SupoClip" width={24} height={24} className="rounded-lg" />
            <span className="text-lg font-bold tracking-tight">SupoClip</span>
          </Link>
          <nav className="flex items-center gap-2" aria-label="Primary navigation">
            <Link href="/blog"><Button variant="ghost" size="sm">Blog</Button></Link>
            <Link href="/sign-up"><Button size="sm">Start clipping</Button></Link>
          </nav>
        </div>
      </header>

      <section className="border-b bg-muted/35">
        <div className="mx-auto max-w-5xl px-6 py-14 md:py-20">
          <Badge variant="secondary">Demo</Badge>
          <h1 className="mt-5 max-w-4xl text-4xl font-extrabold tracking-tight sm:text-5xl" style={{ fontFamily: "var(--font-syne), var(--font-geist-sans), system-ui" }}>
            One long interview in, ready-to-post vertical clips out
          </h1>
          <p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">
            These clips were generated by SupoClip from a public long-form video. Watch them, then jump to the exact
            moment in the original to see what the AI picked and how it reframed it.
          </p>
          <a href={DEMO_SOURCE.url} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex items-center gap-3 rounded-lg border bg-background p-3 pr-4 text-sm transition-colors hover:border-foreground/30">
            <span className="flex h-9 w-9 items-center justify-center rounded-md bg-red-500/10"><Youtube className="h-4 w-4 text-red-500" /></span>
            <span>
              <span className="block font-medium">{DEMO_SOURCE.title}</span>
              <span className="block text-xs text-muted-foreground">Source video on YouTube</span>
            </span>
            <ExternalLink className="h-3.5 w-3.5 text-muted-foreground" />
          </a>
        </div>
      </section>

      <div className="mx-auto max-w-5xl px-6 py-12 md:py-16">
        <section aria-labelledby="clips-heading">
          <h2 id="clips-heading" className="text-3xl font-bold tracking-tight">The clips</h2>
          <div className="mt-8 grid gap-10 md:grid-cols-2">
            {DEMO_CLIPS.map((clip) => (
              <article key={clip.id} id={clip.id} className="scroll-mt-8">
                <video
                  src={clip.src}
                  poster={clip.poster}
                  controls
                  playsInline
                  preload="none"
                  width={540}
                  height={960}
                  className="mx-auto aspect-[9/16] w-full max-w-[300px] rounded-xl bg-black shadow-lg ring-1 ring-border"
                  aria-label={`SupoClip clip: ${clip.hook}`}
                />
                <h3 className="mt-5 text-center text-lg font-semibold">{clip.hook}</h3>
                <p className="mt-1 text-center text-sm tabular-nums text-muted-foreground">
                  Source {clip.range} · full clip {clip.duration}
                </p>
                <p className="mt-3 text-center text-sm">
                  <a href={getDemoSourceMomentUrl(clip)} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 font-medium underline underline-offset-4">
                    Watch this moment in the original <ExternalLink className="h-3.5 w-3.5" />
                  </a>
                </p>
              </article>
            ))}
          </div>
          <aside className="mt-10 flex gap-3 rounded-lg border bg-muted/40 p-5 text-sm leading-7 text-muted-foreground">
            <Info className="mt-1 h-4 w-4 shrink-0" />
            <p>
              <strong className="text-foreground">About these previews.</strong> To keep this page fast, the files above are
              shortened ({DEMO_CLIPS.map((clip) => `${clip.previewSeconds}s`).join(" and ")}) and downscaled to 540×960. SupoClip renders full
              clips at 1080×1920. We don&apos;t show virality scores or speed numbers here because one demo can&apos;t support those
              claims. The best test is a recording of your own.
            </p>
          </aside>
        </section>

        <section className="mt-16" aria-labelledby="pipeline-heading">
          <h2 id="pipeline-heading" className="text-3xl font-bold tracking-tight">What SupoClip did</h2>
          <ol className="mt-8 grid gap-4 sm:grid-cols-2">
            {pipeline.map(({ icon: Icon, title: stepTitle, detail }, index) => (
              <li key={stepTitle} className="rounded-lg border p-5">
                <div className="flex items-center justify-between">
                  <Icon className="h-5 w-5" />
                  <span className="font-mono text-xs text-muted-foreground">0{index + 1}</span>
                </div>
                <h3 className="mt-4 font-semibold">{stepTitle}</h3>
                <p className="mt-1 text-sm leading-6 text-muted-foreground">{detail}</p>
              </li>
            ))}
          </ol>
          <p className="mt-6 text-sm leading-7 text-muted-foreground">
            Captions are timed word by word, and the active word is highlighted. The same pipeline runs in the hosted app
            and in a <Link href={SELF_HOSTING_GUIDE_HREF} className="font-medium text-foreground underline underline-offset-4">self-hosted install</Link>;
            the <Link href="/ai-video-clipper" className="font-medium text-foreground underline underline-offset-4">AI video clipper guide</Link> covers each stage.
          </p>
        </section>

        <section className="mt-16 rounded-2xl border bg-foreground p-6 text-background md:p-8">
          <h2 className="text-2xl font-bold tracking-tight">Run it on your own video</h2>
          <p className="mt-2 max-w-xl text-sm leading-6 text-background/70">
            Paste a YouTube link or upload a file. Review the suggested clips, adjust the captions, and export for Shorts, Reels, or TikTok.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Link href="/sign-up"><Button variant="secondary">Start clipping <ArrowRight className="h-4 w-4" /></Button></Link>
            <a href={GITHUB_URL} target="_blank" rel="noopener noreferrer">
              <Button variant="outline" className="border-background/30 bg-transparent text-background hover:bg-background hover:text-foreground">
                <Github className="h-4 w-4" /> Self-host from GitHub
              </Button>
            </a>
          </div>
        </section>

        <div className="mt-16 border-t pt-12">
          <RelatedGuides href="/demo" />
        </div>
      </div>
      <SiteFooter />
    </main>
  );
}
